; VRAM Layout — Mode 1
; Generated by VRAM Layout Planner
; 2026-04-03T16:21:55.455Z

VRAM_BG1_TILES_START = 0x0000  ; BG1 Tiles — start
VRAM_BG1_TILES_SIZE  = $1000  ; 4096 bytes
VRAM_BG1_TILES_END   = 0x1000  ; BG1 Tiles — end (exclusive)
; Note: 4bpp, 32 tiles

VRAM_BG2_TILES_START = 0x1000  ; BG2 Tiles — start
VRAM_BG2_TILES_SIZE  = $1000  ; 4096 bytes
VRAM_BG2_TILES_END   = 0x2000  ; BG2 Tiles — end (exclusive)
; Note: 4bpp, 32 tiles

VRAM_BG3_TILES_START = 0x2000  ; BG3 Tiles — start
VRAM_BG3_TILES_SIZE  = $0400  ; 1024 bytes
VRAM_BG3_TILES_END   = 0x2400  ; BG3 Tiles — end (exclusive)
; Note: 2bpp, 16 tiles

VRAM_BG1_MAP_START = 0x4000  ; BG1 Map — start
VRAM_BG1_MAP_SIZE  = $0800  ; 2048 bytes
VRAM_BG1_MAP_END   = 0x4800  ; BG1 Map — end (exclusive)
; Note: 32x32 screen

VRAM_BG2_MAP_START = 0x4800  ; BG2 Map — start
VRAM_BG2_MAP_SIZE  = $0800  ; 2048 bytes
VRAM_BG2_MAP_END   = 0x5000  ; BG2 Map — end (exclusive)
; Note: 32x32 screen

VRAM_BG3_MAP_START = 0x5000  ; BG3 Map — start
VRAM_BG3_MAP_SIZE  = $0800  ; 2048 bytes
VRAM_BG3_MAP_END   = 0x5800  ; BG3 Map — end (exclusive)
; Note: 32x32 screen

VRAM_OBJ_TILES_START = 0x8000  ; OBJ Tiles — start
VRAM_OBJ_TILES_SIZE  = $4000  ; 16384 bytes
VRAM_OBJ_TILES_END   = 0xC000  ; OBJ Tiles — end (exclusive)
; Note: 4bpp, 512 tiles
