import type { VramBlock, Scene, ProjectData, ObselConfig } from "../types";
import { fmtHex, toConstantName } from "./format";
import { obselRegValue } from "./registers";

/**
 * Compute PPU register helpers for SNES VRAM blocks.
 */
function ppuRegComment(block: VramBlock): string[] {
  const byteAddr = block.startWord * 2;
  const comments: string[] = [];

  if (block.category === "bg-tiles") {
    const nba = (byteAddr >> 12) & 0x0F;
    const aligned = (byteAddr & 0x1FFF) === 0;
    comments.push(`; BGxNBA value: $${nba.toString(16).toUpperCase().padStart(2, "0")}${aligned ? "" : "  ⚠ NOT 8KB-aligned!"}`);
  } else if (block.category === "bg-map") {
    const sc = (byteAddr >> 8) & 0xFC;
    const aligned = (byteAddr & 0x07FF) === 0;
    comments.push(`; BGxSC base: $${sc.toString(16).toUpperCase().padStart(2, "0")}${aligned ? "" : "  ⚠ NOT 2KB-aligned!"}`);
  } else if (block.category === "obj-tiles") {
    const nameBase = (byteAddr >> 13) & 0x07;
    const aligned = (byteAddr & 0x1FFF) === 0;
    comments.push(`; OBSEL name base: ${nameBase}${aligned ? "" : "  ⚠ NOT 8KB-aligned!"}`);
  } else if (block.category === "mode7-tiles") {
    if (byteAddr !== 0) {
      comments.push(`; ⚠ Mode 7 tile data must start at $0000`);
    }
  }

  return comments;
}

const fmtByteHex = (wordAddr: number) => fmtHex(wordAddr);

export type AsmFormat = "ca65" | "asar" | "wla";

const ASM_CONST: Record<AsmFormat, (name: string, value: string, comment: string) => string> = {
  "ca65":  (n, v, c) => `${n} = ${v}  ; ${c}`,
  "asar":  (n, v, c) => `!${n} = ${v}  ; ${c}`,
  "wla":   (n, v, c) => `.define ${n} ${v}  ; ${c}`,
};

export function exportAsAsm(blocks: VramBlock[], modeName: string, obsel: ObselConfig, format: AsmFormat = "ca65"): string {
  const sorted = [...blocks].sort((a, b) => a.startWord - b.startWord);
  const lines = [
    `; VRAM Layout — ${modeName}`,
    `; Generated by SNES VRAM Planner`,
    `; ${new Date().toISOString()}`,
    `;`,
    `; Addresses are byte addresses ($0000–$FFFF = 64KB)`,
    `; 1 word = 2 bytes; VRAM is 32768 words total`,
    "",
    `; ── OBSEL ($2101) ──────────────────────────────────`,
    ASM_CONST[format]("OBSEL_VALUE", `$${obselRegValue(obsel.nameBaseWord, obsel.gap, obsel.objSize ?? 0).toString(16).toUpperCase().padStart(2, "0")}`, "$2101"),
    ASM_CONST[format]("OBJ_PAGE0", fmtByteHex(obsel.nameBaseWord), "OBJ tiles 0-255"),
    ASM_CONST[format]("OBJ_PAGE1", fmtByteHex(obsel.nameBaseWord + obsel.gap), "OBJ tiles 256-511"),
    "",
  ];
  for (const b of sorted) {
    const name     = toConstantName(b.label);
    const start    = fmtHex(b.startWord);
    const end      = fmtHex(b.startWord + b.sizeWords);
    const sizeHex  = `$${(b.sizeWords * 2).toString(16).toUpperCase().padStart(4, "0")}`;
    const sizeBytes = b.sizeWords * 2;

    const c = ASM_CONST[format];
    lines.push(c(`${name}_START`, start, `${b.label} — start`));
    lines.push(c(`${name}_SIZE`, sizeHex, `${sizeBytes} bytes`));
    lines.push(c(`${name}_END`, end, `${b.label} — end (exclusive)`));

    const regComments = ppuRegComment(b);
    for (const rc of regComments) {
      lines.push(rc);
    }

    if (b.note) lines.push(`; Note: ${b.note}`);
    lines.push("");
  }
  return lines.join("\n");
}

export function exportSceneAsJson(scene: Scene): string {
  return JSON.stringify(scene, null, 2);
}

export function exportProjectAsJson(scenes: Scene[], activeSceneId: string): string {
  const project: ProjectData = {
    version: 2,
    scenes,
    activeSceneId,
    darkMode: false,
  };
  return JSON.stringify(project, null, 2);
}

// Legacy compat
export function exportAsJson(blocks: VramBlock[]): string {
  return JSON.stringify(blocks, null, 2);
}
