import { describe, it, expect } from "vitest";
import { exportAsAsm, exportAsJson } from "./export";
import type { VramBlock, ObselConfig } from "../types";

function makeBlock(overrides: Partial<VramBlock> = {}): VramBlock {
  return {
    id: "test-1",
    label: "BG1 Tiles",
    startWord: 0,
    sizeWords: 2048,
    category: "bg-tiles",
    color: "blue",
    locked: false,
    note: "",
    ...overrides,
  };
}

const defaultObsel: ObselConfig = { nameBaseWord: 0x4000, gap: 0x1000 };

describe("exportAsAsm", () => {
  it("exports empty blocks with header only", () => {
    const result = exportAsAsm([], "Mode 1", defaultObsel);
    expect(result).toContain("; VRAM Layout — Mode 1");
    expect(result).toContain("; Generated by SNES VRAM Planner");
  });

  it("exports a single block correctly", () => {
    const block = makeBlock();
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("VRAM_BG1_TILES_START = $0000");
    expect(result).toContain("VRAM_BG1_TILES_SIZE");
    expect(result).toContain("VRAM_BG1_TILES_END");
  });

  it("includes block notes", () => {
    const block = makeBlock({ note: "Important note" });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("; Note: Important note");
  });

  it("sorts blocks by startWord", () => {
    const blockA = makeBlock({ id: "a", label: "Second", startWord: 2048 });
    const blockB = makeBlock({ id: "b", label: "First", startWord: 0 });
    const result = exportAsAsm([blockA, blockB], "Mode 1", defaultObsel);
    const lines = result.split("\n");
    const firstBlockLine = lines.findIndex(l => l.includes("VRAM_FIRST"));
    const secondBlockLine = lines.findIndex(l => l.includes("VRAM_SECOND"));
    expect(firstBlockLine).toBeLessThan(secondBlockLine);
  });

  it("includes PPU register comment for bg-tiles (BGxNBA)", () => {
    const block = makeBlock({ category: "bg-tiles", startWord: 0 });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("; BGxNBA value:");
  });

  it("includes PPU register comment for bg-map (BGxSC)", () => {
    const block = makeBlock({ id: "map", label: "BG1 Map", category: "bg-map", startWord: 8192 });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("; BGxSC base:");
  });

  it("includes PPU register comment for obj-tiles (OBSEL)", () => {
    const block = makeBlock({ id: "obj", label: "OBJ", category: "obj-tiles", startWord: 16384 });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("; OBSEL name base:");
  });

  it("includes alignment warning in PPU comment for misaligned bg-tiles", () => {
    const block = makeBlock({ category: "bg-tiles", startWord: 100 });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).toContain("NOT 8KB-aligned");
  });

  it("uses $ prefix for all hex addresses", () => {
    const block = makeBlock({ startWord: 4096 });
    const result = exportAsAsm([block], "Mode 1", defaultObsel);
    expect(result).not.toContain("0x");
    expect(result).toContain("$2000");
  });

  it("includes OBSEL register constants", () => {
    const result = exportAsAsm([], "Mode 1", defaultObsel);
    expect(result).toContain("OBSEL_VALUE");
    expect(result).toContain("OBJ_PAGE0");
    expect(result).toContain("OBJ_PAGE1");
  });

  it("includes header with addressing notes", () => {
    const result = exportAsAsm([], "Mode 1", defaultObsel);
    expect(result).toContain("Addresses are byte addresses");
  });
});

describe("exportAsJson", () => {
  it("exports empty array", () => {
    expect(exportAsJson([])).toBe("[]");
  });

  it("exports blocks as formatted JSON", () => {
    const block = makeBlock();
    const result = exportAsJson([block]);
    const parsed = JSON.parse(result);
    expect(parsed).toHaveLength(1);
    expect(parsed[0].label).toBe("BG1 Tiles");
    expect(parsed[0].startWord).toBe(0);
  });
});
