import type { VramBlock } from "../types";
import { fmtHex, toConstantName } from "./format";

/**
 * Compute PPU register helpers for SNES VRAM blocks.
 * BGxNBA: character base = byte_address >> 12 (8KB granularity, 4-bit value 0-F)
 * BGxSC:  screen base = (byte_address >> 8) & $FC (2KB granularity, stored in bits 2-6)
 * OBSEL:  name base = (byte_address >> 13) & $07 (bits 1-2), name select = bits 3-4
 */
function ppuRegComment(block: VramBlock): string[] {
  const byteAddr = block.startWord * 2;
  const comments: string[] = [];

  if (block.category === "bg-tiles") {
    const nba = (byteAddr >> 12) & 0x0F;
    const aligned = (byteAddr & 0x1FFF) === 0;
    comments.push(`; BGxNBA value: $${nba.toString(16).toUpperCase().padStart(2, "0")}${aligned ? "" : "  ⚠ NOT 8KB-aligned!"}`);
  } else if (block.category === "bg-map") {
    const sc = (byteAddr >> 8) & 0xFC;
    const aligned = (byteAddr & 0x07FF) === 0;
    comments.push(`; BGxSC base: $${sc.toString(16).toUpperCase().padStart(2, "0")}${aligned ? "" : "  ⚠ NOT 2KB-aligned!"}`);
  } else if (block.category === "obj-tiles") {
    const nameBase = (byteAddr >> 13) & 0x07;
    const aligned = (byteAddr & 0x1FFF) === 0;
    comments.push(`; OBSEL name base: ${nameBase}${aligned ? "" : "  ⚠ NOT 8KB-aligned!"}`);
  } else if (block.category === "mode7-tiles") {
    if (byteAddr !== 0) {
      comments.push(`; ⚠ Mode 7 tile data must start at $0000`);
    }
  }

  return comments;
}

export function exportAsAsm(blocks: VramBlock[], modeName: string): string {
  const sorted = [...blocks].sort((a, b) => a.startWord - b.startWord);
  const lines = [
    `; VRAM Layout — ${modeName}`,
    `; Generated by VRAM Layout Planner`,
    `; ${new Date().toISOString()}`,
    `;`,
    `; Addresses are byte addresses ($0000–$FFFF = 64KB)`,
    `; 1 word = 2 bytes; VRAM is 32768 words total`,
    "",
  ];
  for (const b of sorted) {
    const name     = toConstantName(b.label);
    const start    = fmtHex(b.startWord);
    const end      = fmtHex(b.startWord + b.sizeWords);
    const sizeHex  = `$${(b.sizeWords * 2).toString(16).toUpperCase().padStart(4, "0")}`;
    const sizeBytes = b.sizeWords * 2;

    lines.push(`${name}_START = ${start}  ; ${b.label} — start`);
    lines.push(`${name}_SIZE  = ${sizeHex}  ; ${sizeBytes} bytes`);
    lines.push(`${name}_END   = ${end}  ; ${b.label} — end (exclusive)`);

    // PPU register helpers
    const regComments = ppuRegComment(b);
    for (const rc of regComments) {
      lines.push(rc);
    }

    if (b.note) lines.push(`; Note: ${b.note}`);
    lines.push("");
  }
  return lines.join("\n");
}

export function exportAsJson(blocks: VramBlock[]): string {
  return JSON.stringify(blocks, null, 2);
}
