import type { VramBlock, ObselConfig, ObselGap, SnesMode } from "../types";

export interface PpuRegisters {
  bg1sc: number; bg2sc: number; bg3sc: number; bg4sc: number;
  bg12nba: number; bg34nba: number;
  obsel: number;
}

export function obselRegValue(nameBaseWord: number, gap: ObselGap, objSize = 0): number {
  const nameBaseField = (nameBaseWord * 2) / 0x2000;
  let nameSelectField = 0;
  if (gap === 0x1000) nameSelectField = 0;
  else if (gap === 0x2000) nameSelectField = 1;
  else if (gap === 0x4000) nameSelectField = 2;
  return ((objSize & 0x07) << 5) | (nameSelectField << 3) | (nameBaseField & 0x07);
}

/**
 * Compute PPU register values from the current layout.
 * Scans blocks to find BG tile and map data, derives register fields.
 */
export function computePpuRegisters(blocks: VramBlock[], _mode: SnesMode, obsel: ObselConfig): PpuRegisters {
  // Match blocks to BG layers using explicit bgLayer assignment, fallback to sort order
  const bgTiles: (VramBlock | undefined)[] = [undefined, undefined, undefined, undefined];
  const bgMaps: (VramBlock | undefined)[] = [undefined, undefined, undefined, undefined];

  const unassignedTiles: VramBlock[] = [];
  const unassignedMaps: VramBlock[] = [];

  for (const b of blocks) {
    if (b.category === "bg-tiles") {
      if (b.bgLayer && !bgTiles[b.bgLayer - 1]) bgTiles[b.bgLayer - 1] = b;
      else unassignedTiles.push(b);
    } else if (b.category === "bg-map") {
      if (b.bgLayer && !bgMaps[b.bgLayer - 1]) bgMaps[b.bgLayer - 1] = b;
      else unassignedMaps.push(b);
    }
  }
  // Fill remaining slots with unassigned blocks by address order
  unassignedTiles.sort((a, b) => a.startWord - b.startWord);
  unassignedMaps.sort((a, b) => a.startWord - b.startWord);
  for (let i = 0; i < 4; i++) {
    if (!bgTiles[i] && unassignedTiles.length) bgTiles[i] = unassignedTiles.shift();
    if (!bgMaps[i] && unassignedMaps.length) bgMaps[i] = unassignedMaps.shift();
  }

  // BGxSC: screen base address in bits 2-6, map size in bits 0-1
  function bgsc(mapBlock: VramBlock | undefined): number {
    if (!mapBlock) return 0;
    const byteAddr = mapBlock.startWord * 2;
    const scBase = (byteAddr >> 8) & 0xFC;
    const mapSizeBits = mapBlock.mapSize
      ? { "32x32": 0, "64x32": 1, "32x64": 2, "64x64": 3 }[mapBlock.mapSize] ?? 0
      : 0;
    return scBase | mapSizeBits;
  }

  // BGxNBA: character base in 8KB units
  // BG12NBA: BG1 in low nibble, BG2 in high nibble
  // BG34NBA: BG3 in low nibble, BG4 in high nibble
  function nbaField(tileBlock: VramBlock | undefined): number {
    if (!tileBlock) return 0;
    const byteAddr = tileBlock.startWord * 2;
    return (byteAddr >> 12) & 0x0F;
  }

  return {
    bg1sc: bgsc(bgMaps[0]),
    bg2sc: bgsc(bgMaps[1]),
    bg3sc: bgsc(bgMaps[2]),
    bg4sc: bgsc(bgMaps[3]),
    bg12nba: (nbaField(bgTiles[1]) << 4) | nbaField(bgTiles[0]),
    bg34nba: (nbaField(bgTiles[3]) << 4) | nbaField(bgTiles[2]),
    obsel: obselRegValue(obsel.nameBaseWord, obsel.gap, obsel.objSize ?? 0),
  };
}

export function formatRegistersAsAsm(regs: PpuRegisters, mode: SnesMode): string {
  const hex = (v: number) => "$" + v.toString(16).toUpperCase().padStart(2, "0");
  const lines = [
    `; PPU Register Values — ${mode.label}`,
    `; Generated by SNES VRAM Planner`,
    "",
  ];

  for (let i = 0; i < mode.bgCount; i++) {
    const val = [regs.bg1sc, regs.bg2sc, regs.bg3sc, regs.bg4sc][i];
    lines.push(`BG${i + 1}SC    = ${hex(val)}  ; $210${7 + i}`);
  }
  lines.push(`BG12NBA  = ${hex(regs.bg12nba)}  ; $210B`);
  if (mode.bgCount > 2) {
    lines.push(`BG34NBA  = ${hex(regs.bg34nba)}  ; $210C`);
  }
  lines.push(`OBSEL    = ${hex(regs.obsel)}  ; $2101`);

  return lines.join("\n");
}
